baseURL = "https://<YOUR-DOMAIN>/"
languageCode = "en-us"
title = "<BLOG-NAME>"
theme = "<THEME-NAME>"

[params]
env = "production"
description = "AI Agent Technical Blog"
defaultTheme = "dark"

[params.cover]
responsiveImages = true
hidden = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10
